#include <Arduino.h>
#include <avr/interrupt.h>
#include <avr/io.h>
#include <inttypes.h>
#include <stdlib.h>
#include "AVR_CS.h"


#define Hz_10 6250  // compare match register 16MHz/256/10Hz
#define Hz_2  31250 // compare match register 16MHz/256/2Hz
#define Hz_2k 31    // compare match register 16MHz/256/2kHz

#define STACK_SIZE_DEFAULT 100

#define RED_LED     5
#define TICK_LED    6
#define CS_LED      7

typedef struct {
    volatile uint8_t* stack_ptr;    // Pointer to the address of the task's 'private' stack in memory
    uint8_t stack[STACK_SIZE_DEFAULT];
    void (*function_pointer)(void); // Pointer to task function.
    uint16_t program_counter;       // Pointer to the next instruction to be ran of this task.
    uint8_t frequency;              // Holds interval of ticks between activations.
    uint8_t _cnt_to_activation;     // Counts to zero. Activate function on zero.
} Task_cenas;

void vPortYieldFromTick( void ) __attribute__ ( ( naked ) );
void vTaskIncrementTick( void );
void vTaskSwitchContext( void );
uint8_t *pxPortInitialiseStack( uint8_t* topOfStack, void (*pxCode)(), void *pvParameters );

void hardwareInit(int comp){
    noInterrupts();  // disable all interrupts
    
    pinMode(PD2, OUTPUT);
    pinMode(PD3, OUTPUT);
    pinMode(PD4, OUTPUT);
    pinMode(PD5, OUTPUT);
    pinMode(PD6, OUTPUT);
    pinMode(PD7, OUTPUT);

    TCCR1A = 0;
    TCCR1B = 0;
    TCNT1 = 0;
    
    OCR1A = comp;
    TCCR1B |= (1 << WGM12);     // CTC mode
    TCCR1B |= (1 << CS12);      // 256 prescaler
    TIMSK1 |= (1 << OCIE1A);    // enable timer compare interrupt

    interrupts();  // enable all interrupts
}

#define TASK(name, code) \
 void name##_f(void); \
 Task_cenas name = { \
    .function_pointer = name##_f , \
    .stack_ptr = 0, \
    .frequency = 0, \
    ._cnt_to_activation = 0 \
 }; \
 void name##_f(void) { \
    while (true) { \
        code \
    } \
    return; \
 }

TASK(t1, {
    for(uint32_t i = 500000; i > 0; i--) {
        asm("nop");
    }
    PORTD ^= _BV(2);    // Toggle
    PORTD |= _BV(RED_LED);    // Enable
});

TASK(t2, {
    for(uint32_t i = 500000; i > 0; i--) {
        asm("nop");
    }
    PORTD ^= _BV(3);    // Toggle
    PORTD &= ~_BV(RED_LED);   // Disable
});

TASK(t3, {
    for(uint32_t i = 500000; i > 0; i--) {
        asm("nop");
    }
    PORTD ^= _BV(4);    // Toggle
    PORTD ^= _BV(RED_LED);    // Pisca-pisca no ma no ma ei
});


void addTask(Task_cenas* task) {
    task->stack_ptr = pxPortInitialiseStack(task->stack+STACK_SIZE_DEFAULT, task->function_pointer, 0);
    return;
}

uint16_t test = 0;
volatile void* volatile pxCurrentTCB = &test;

uint8_t *pxPortInitialiseStack( uint8_t* topOfStack, void (*pxCode)(), void *pvParameters ) {
    uint16_t usAddress;
    /* Simulate how the stack would look after a call to vPortYield() generated by
    the compiler. */

    /* The start of the task code will be popped off the stack last, so place
    it on first. */
    usAddress = ( uint16_t ) pxCode;
    *topOfStack = ( uint8_t ) ( usAddress & ( uint16_t ) 0x00ff );
    topOfStack--;

    usAddress >>= 8;
    *topOfStack = ( uint8_t ) ( usAddress & ( uint16_t ) 0x00ff );
    topOfStack--;

    /* Next simulate the stack as if after a call to portSAVE_CONTEXT().
    portSAVE_CONTEXT places the flags on the stack immediately after r0
    to ensure the interrupts get disabled as soon as possible, and so ensuring
    the stack use is minimal should a context switch interrupt occur. */
    *topOfStack = ( uint8_t ) 0x00;    /* R0 */
    topOfStack--;
    *topOfStack = ( (uint8_t) 0x80 );
    topOfStack--;

    /* Now the remaining registers. The compiler expects R1 to be 0. */
    *topOfStack = ( uint8_t ) 0x00;    /* R1 */

    /* Leave R2 - R23 untouched */
    topOfStack -= 23;

    /* Place the parameter on the stack in the expected location. */
    usAddress = ( uint16_t ) pvParameters;
    *topOfStack = ( uint8_t ) ( usAddress & ( uint16_t ) 0x00ff );
    topOfStack--;

    usAddress >>= 8;
    *topOfStack = ( uint8_t ) ( usAddress & ( uint16_t ) 0x00ff );

    /* Leave register R26 - R31 untouched */
    topOfStack -= 7;

    return topOfStack;
}

void vPortYieldFromTick( void ) {
    // This is a naked function so the context
    // is saved. 
    portSAVE_CONTEXT();

    PORTD ^= _BV(TICK_LED);

    // Increment the tick count and check to see
    // if the new tick value has caused a delay
    // period to expire. This function call can
    // cause a task to become ready to run.
    vTaskIncrementTick();
    
    // See if a context switch is required.
    // Switch to the context of a task made ready
    // to run by vTaskIncrementTick() if it has a
    // priority higher than the interrupted task.
    vTaskSwitchContext();
    
    // Restore the context. If a context switch
    // has occurred this will restore the context of
    // the task being resumed.
    portRESTORE_CONTEXT();
    
    // Return from this naked function.
    asm volatile ( "ret" );
}

uint8_t cnt = 20;
int task = 0;

void vTaskIncrementTick() {
    // TODO
    if (cnt) {
        cnt--;
    } else {
        cnt = 20;
    }
    
    return;
}

void vTaskSwitchContext() {

    if (!cnt) {
        PORTD ^= _BV(CS_LED);
        if (task == 0) {
            task = 1;
            PORTD ^= _BV(2);    // Toggle
            pxCurrentTCB = &t1.stack_ptr;
        } else if (task == 1) {
            task = 2;
            PORTD ^= _BV(3);    // Toggle
            pxCurrentTCB = &t2.stack_ptr;
        } else if (task == 2) {
            task = 3;
            PORTD ^= _BV(4);    // Toggle
            pxCurrentTCB = &t3.stack_ptr;
        } else if (task == 3) {
            task = 1;
            PORTD ^= _BV(2);    // Toggle
            pxCurrentTCB = &t1.stack_ptr;
        }
    }
    return;
}

ISR(TIMER1_COMPA_vect, ISR_NAKED) {
    /* Call the tick function. */
    vPortYieldFromTick();

    /* Return from the interrupt. If a context
    switch has occurred this will return to a
    different task. */
    asm volatile ( "reti" );
}

int main() {
    addTask(&t1);
    addTask(&t2);
    addTask(&t3);

    hardwareInit(Hz_10);
    while (true) {
        asm("nop");
    }
}
